name: PROBLEM
version: 0.2.0.0
github: "tomasaschan/advent-of-code-2018"
license: MIT
author: "Tomas Aschan"
maintainer: "1550920+tomasaschan@users.noreply.github.com"
copyright: "2018 Tomas Aschan"

library:
  source-dirs: lib
  ghc-options:
    - -Wall
  dependencies:
    - base
    - utils

executables:
  PROBLEM:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - PROBLEM
      - base
      - utils

tests:
  PROBLEM-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - PROBLEM
      - base
      - hspec
      - QuickCheck
