name: aoc
version: 2018.12.0.0
github: "tomasaschan/advent-of-code-2018"
license: BSD3
author: "Tomas Aschan"
maintainer: "1550920+tomasaschan@users.noreply.github.com"
copyright: "2018 Tomas Aschan"

extra-source-files:
  - README.md
  - ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/tomasaschan/advent-of-code-2018#readme>

dependencies:
  - base
  - containers

library:
  source-dirs: src
  dependencies:
    - digits
    - graphite
    - hashable
    - parsec
    - PSQueue
    - split
    - sort
    - Unique
  ghc-options:
    - -Wall
    - -O2

executables:
  aoc:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - aoc
      - directory
  p15:
    main: Main.hs
    source-dirs: p15
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - aoc
      - directory
      - ansi-terminal
      - mtl
      - transformers
      - optparse-applicative

tests:
  aoc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - aoc
      - digits
      - hspec
      - parsec
      - PSQueue
      - QuickCheck
