resolver: ghc-8.4.3
packages:
  - .
extra-deps:
  # - ghc-paths-0.1.0.9
  # - network-2.8.0.0
  - random-1.1
  # - syb-0.7
  - hspec-2.6.0
  - hspec-core-2.6.0
  - hspec-discover-2.6.0
  - hspec-expectations-0.8.2
  - QuickCheck-2.12.6.1
  - HUnit-1.6.0.0
  - ansi-terminal-0.8.2
  - call-stack-0.1.0
  - clock-0.7.2
  - quickcheck-io-0.2.0
  - setenv-0.1.1.3
  - tf-random-0.5
  - colour-2.3.4
  - mintty-0.1.2
  - primitive-0.6.4.0
  - erf-2.0.0.0
  - split-0.2.3.3
  - containers-0.6.0.1
flags: {}
extra-package-dbs: []
allow-newer: true
