resolver: lts-13.27
packages:
  - utils
  - p01
  - p02
  - p03
  - p04
  - p05
  - p06
  # PROBLEM
extra-deps:
  - graphite-0.9.8.0
  - PSQueue-1.1.0.1
  - Unique-0.4.7.5
flags: {}
extra-package-dbs: []
