resolver: lts-13.27
packages:
  - utils
  - p01
  - p02
  - p03
  - p04
  - p05
  - p06
  - p07
  - p08
  - p09
  - p10
  - p11
  - p12
  # PROBLEM
extra-deps:
  - graphite-0.9.8.0
  - graphviz-2999.20.0.3
  - PSQueue-1.1.0.1
  - Unique-0.4.7.5
flags: {}
extra-package-dbs: []
